"""migrasi data siswa

Revision ID: ecbd62769d7f
Revises: 4992e2b07b76
Create Date: 2024-06-27 21:33:37.965665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecbd62769d7f'
down_revision = '4992e2b07b76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('siswa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_siswa', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('kelas', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('siswa', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_siswa_id_siswa'), ['id_siswa'], unique=False)
        batch_op.create_index(batch_op.f('ix_siswa_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('siswa', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_siswa_name'))
        batch_op.drop_index(batch_op.f('ix_siswa_id_siswa'))

    op.drop_table('siswa')
    # ### end Alembic commands ###
